DOMAIN = "intergas_local"
DEFAULT_SCAN_INTERVAL = 120

ERROR_CODES = {
    0: "-",
    1: "defrost_failed",
    2: "low_pressure",
    3: "high_pressure",
    4: "compressor_outside_op_range",
    5: "exhaust_temp_too_high",
    6: "condensor_temp_too_high",
    7: "outdoorunit_specific_auto_restart",
    8: "outdoorunit_specific_locked",
    9: "outdoorunit_control_guard",
    10: "water_flow_too_low",
    11: "water_flow_too_low_defrost",
    12: "condensor_gas_too_low",
    13: "no_outdoor_sensor",
    14: "pumpdown_failed",
    15: "dsh_too_low",
    16: "ssh_too_low",
    17: "ssh_too_high",
    18: "cooling_mode_temps",
    19: "condensor_liquid_sensor",
    20: "xtp_device_water_inlet",
    21: "xtp_device_water_outlet",
    22: "xtp_device_refrigerant_liquid",
    23: "xtp_device_refrigerant_gas",
    128: "ac_bus_voltage_high",
    129: "ac_bus_voltage_low",
    130: "dc_bus_overvoltage",
    131: "compressor_overcurrent_hardware",
    132: "compressor_overcurrent_firmware",
    133: "ac_input_overcurrent_hardware",
    134: "ac_input_overcurrent_firmware",
    135: "compressor_current_overload",
    136: "phase_loss_loss_of_synchronism",
    137: "ipm_temp_protection",
    138: "outdoor_dc_fan_fault",
    139: "suction_temp_sensor_error",
    140: "odu_discharge_temp_sensor_error",
    141: "odu_coil_temp_sensor_error",
    142: "ambient_temp_sensor_error",
    143: "discharge_temp_high_error",
    144: "condensing_temp_high_error",
    145: "odu_idu_communication_error",
    146: "dc_bus_undervoltage",
    255: "no_error",
}

HEAT_PUMP_MODES = {
    0: "Dhw",
    1: "Heating",
    2: "Cooling",
    253: "Pumpdown",
    254: "Off",
    255: "Undefined",
}

WORKING_MODES = {
    0: "Cooling",
    1: "Heating",
    2: "Defrosting",
    3: "Pumpdown",
    255: "Undefined",
}

NOTIFICATION_CODES = {
    0: "PARAMETER_OUT_OF_BOUNDS",
    1: "LOW_PRESSURE",
    2: "NO_PRESSURE",
    8: "XTP_FAULT_HP_OFF",
    9: "HEATPUMP_SELECT_PHASE",
    10: "HEATPUMP_REMOTE_OF",
    11: "HEATPUMP_FAILED",
    12: "KWH_METER",
    13: "CONDENSOR_OVERHEAT",
    14: "ROOMTHERM_FAILED",
    15: "CRANKHEATER",
    16: "WATER_TEMP_SENSORS",
    18: "EEPROM_BROKEN",
    19: "BMM_BROKEN",
    20: "NO_FLOW_DHW_CIRCUIT",
    21: "NO_FLOW_CH_CIRCUIT",
    22: "FLOW_CONTROL_DISABLED",
    23: "COMMISSIONING_LOW_FLOW",
    26: "RTC_TIME_INVALID",
    27: "RTC_CLOCK",
    31: "_UNKNOWN",
    32: "DEFROST_TIMEOUT",
    33: "DEFROST_MONITOR_TIMEOUT",
    37: "SENSOR_HP_RETURN",
    38: "SENSOR_HP_SUPPLY",
    39: "SENSOR_SYSTEM_SUPPLY",
    40: "SENSOR_OUTDOOR",
    41: "SENSOR_CONDENSOR_REF_LIQ",
    42: "SENSOR_CONDENSOR_REF_GAS",
    46: "SENSOR_BOILER_RETURN",
    47: "SENSOR_BOILER_SUPPLY",
    48: "BOILER_FLOW_TOO_HIGH",
    49: "BOILER_FLOW_TOO_LOW",
    50: "BOILER_FLOW_REVERSED",
    51: "BOILER_FAULT",
    52: "BOILER_OPENTHERM_FAULT",
    53: "BOILER_BOILER_SETTING_MAX",
    54: "BOILER_NO_CH_REPONSE",
    60: "THERMOSTAT_VERSION",
    73: "REFRIDGERANT_LOW",
    255: "-",
}

LOCKOUT_CODES = {
    1: "CH_PUMP",
    2: "DHW_PUMP",
    3: "CONDENSOR_OVERHEAT",
    9: "ERROR_DEVICE",
    10: "DEFROST_WATER_TEMP_LOW",
    18: "HEATPUMP_TYPE_UNCONFIGURED",
    19: "BMM_ILLIGAL_SERIAL",
    20: "STORAGEHANDLER_SYNC",
    22: "FIRMWARE_COMPATIBILITY",
    23: "XTP_DEVICE_INTERNAL_FAULT",
    24: "XTP_DEVICE_CONFIG_FAULT",
    25: "XTP_COMMUNICATION_FAULT",
    26: "XTP_START_FAULT",
    31: "ERROR_UNKNOWN",
    37: "SENSOR_HP_RETURN",
    38: "SENSOR_HP_SUPPLY",
    39: "SENSOR_SYSTEM_SUPPLY",
    40: "SENSOR_OUTDOOR",
    42: "SENSOR_CONDENSOR_REF_GAS",
    46: "SENSOR_BOILER_RETURN",
    47: "SENSOR_BOILER_SUPPLY",
    50: "CODE_THERMOSTAT_HEATPUMP",
    51: "CODE_THERMOSTAT_BOILER",
    254: "BYPASS_MODE_ACTIVE",
    255: "-",
}

HEAT_DEMAND_STATUS = {
    0: "opentherm",
    15: "boiler_ext",
    24: "frost",
    37: "ch_rf",
    85: "sensortest",
    86: "commissioning",
    87: "crankheating",
    102: "ch",
    103: "ch_wait",
    104: "defrosting",
    117: "starting_cooling",
    118: "cooling",
    119: "cooling_wait",
    126: "standby",
    127: "off",
    153: "postrun_boiler",
    170: "service",
    189: "postrun_cooling",
    204: "dhw",
    205: "dhw_hreco",
    230: "starting_ch",
    231: "postrun_ch",
    240: "boiler_int",
    255: "heatup",
}

SYSTEM_STATUS = {
    0: "Monitor lockout",
    1: "Pump Venting",
    2: "Service",
    3: "Defrost",
    4: "Domestic Hot Water (DHW)",
    5: "Roomheating Comfort",
    6: "Roomheating Eco",
    7: "Roomcooling",
    8: "DHW Heatexchanger",
    9: "Floor heating protocol",
    12: "Anti freeze",
    13: "Pump maintenance",
    14: "Idle",
    255: "No task",
}

XTREME_BURNER_STATUS = {
    0: "Startup",
    1: "Interpurge",
    2: "Postpurge",
    4: "Prepurge",
    8: "Ignition",
    16: "Waiting",
    32: "Running",
    64: "Rest",
    128: "Lockout",
}

API_CODES = [
    "4133",
    "47e0",
    "503e",
    "5041",
    "5077",
    "5088",
    "50f2",
    "623c",
    "625b",
    "6280",
    "629c",
    "62d1",
    "62e7",
    "63b3",
    "63df",
    "63f0",
    "6505",
    "6578",
    "6579",
    "65a7",
    "65b0",
    "65c1",
    "65d9",
    "6a53",
    "6a8e",
    "6ac5",
    "6c26",
    "6c33",
    "6c53",
    "6c66",
    "6c8a",
    "6ceb",
    "6cfb",
    "7160",
    "71a7",
    "7191",
    "7767",
    "777d",
    "77dd",
    "7921",
    "7940",
    "79b3",
    "7e2c",
    "7e51",
    "7e7a",
    "7ed3",
    "8434",
    "844c",
    "848e",
    "84d1",
    "8e00",
    "8e18",
    "8e1e",
    "8e37",
    "8e7f",
    "8e8f",
    "8ecb",
    "8ecc",
    "8edb",
    "8ef9",
]


def build_resource_url(host: str) -> str:
    value = (host or "").strip()
    if not value:
        raise ValueError("Host is required")
    if "//" not in value:
        value = f"http://{value}"
    value = value.rstrip("/")
    codes = ",".join(dict.fromkeys(API_CODES))
    return f"{value}/api/stats/values?fields={codes}"
